version: "3.9"
services: 
    books_server:
        build:
            dockerfile: "/Dockerfile"
        ports: 
            - "5000:5000"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:5000

    database:
        container_name: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_USER=admin
        image: postgres:15.1-bullseye